version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: your-image-name:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_PROFILES_ACTIVE: dev
      SPRING_LIQUIBASE_PARAMETERS_ADMIN_PASSWORD_BCRYPT: ${ADMIN_PASSWORD_BCRYPT}
      JWT_SECRET_BASE64: ${JWT_SECRET_BASE64}
      JWT_EXPIRATION_MS: 3600000
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: